#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Pregnancy
version:      0.01
version_from: lib/DateTime/Pregnancy.pm
installdirs:  site
requires:
    Test::Pod::Coverage:           0.08
    File::Spec:                    0
    Exporter:                      0
    DateTime:                      0
    POSIX:                         0
    Clone:                         0
    Test::Pod:                     0.95
    Test::More:                    0
    Carp:                          0
    File::Find:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
